language: ruby
rvm:
- 2.2

before_install:
- wget https://github.com/jgm/pandoc/releases/download/1.15.0.6/pandoc-1.15.0.6-1-amd64.deb
- sudo dpkg -i pandoc-1.15.0.6-1-amd64.deb
- rm pandoc-1.15.0.6-1-amd64.deb

script: bundle exec jekyll build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: blog.datacite.org
  endpoint: blog.datacite.org.s3-website-eu-west-1.amazonaws.com
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  on:
    all_branches: true
