language: ruby
rvm:
- 2.3.1

cache: bundler

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="blog.datacite.org";
      RACK_ENV="production";
      CIRNECO_OPTS="";
      cp .env.master .env;
    elif [ "$TRAVIS_BRANCH" == "labs" ]; then
      AWS_BUCKET="blog.labs.datacite.org";
      RACK_ENV="stage";
      CIRNECO_OPTS="";
      cp .env.labs .env;
    else
      exit 1;
    fi
  - rvm install 2.3.1

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -q
  - sudo apt-get install cmake -y

install:
  - bundle install

before_script:
  - cd vendor && npm install
  - cd ..

  - bundle exec cirneco doi mint source/posts $CIRNECO_OPTS;

script:
  - bundle exec middleman build -e $RACK_ENV

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: build
  acl: public_read
  cache_control: "max-age=31536000"
  on:
    all_branches: true

notifications:
  slack: $SLACK_TOKEN
  email: false

after_deploy:
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_NAME}"
  - git config --global push.default simple
  - git remote add upstream https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/datacite/blog.git

  - git add source/posts/.
  - if ! [ -z "$(git status --untracked-files=no --porcelain)" ]; then
      git commit -m 'Committing files changed by cirneco [skip ci]';
      git push upstream HEAD:$TRAVIS_BRANCH;
    fi
