language: ruby
rvm:
- 2.3.1

cache: bundler
cache:
  directories:
    - _frontend/node_modules
    - _frontend/bower_components

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="blog.datacite.org";
      CONFIG_FILE="_config.master.yml";
      JEKYLL_COMMAND="build";
    elif [ "$TRAVIS_BRANCH" == "labs" ]; then
      AWS_BUCKET="blog.labs.datacite.org";
      CONFIG_FILE="_config.labs.yml";
      JEKYLL_COMMAND="build --drafts";
    else
      exit 1;
    fi
  - rvm install 2.2.0

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

before_script:
  - cd _frontend && npm install
  - cd ../ && cp $CONFIG_FILE _config.yml

script:
  - JEKYLL_ENV=production bundle exec jekyll $JEKYLL_COMMAND

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  on:
    all_branches: true

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
