language: ruby
rvm:
- 2.3.1

cache: bundler

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="blog.datacite.org";
      RACK_ENV="production";
    elif [ "$TRAVIS_BRANCH" == "labs" ]; then
      AWS_BUCKET="blog.labs.datacite.org";
      RACK_ENV="stage";
      cp .env.labs .env;
    else
      exit 1;
    fi
  - rvm install 2.3.1

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

install:
  - bundle install

before_script:
  - cd vendor && npm install
  - cd ..

script:
  - bundle exec middleman build -e $RACK_ENV

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: build
  acl: public_read
  cache_control: "max-age=31536000"
  on:
    all_branches: true

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
